### Create a user
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Jesse",
    "lastName": "Juwe",
    "email": "jesse.juwe@gotrustcrow.com",
    "phoneNumber": "08012345678",
    "password": "password123#",
    "role": "USER"
}