### Create a user
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jane.doe@example.com",
    "phoneNumber": "08012345678",
    "password": "password123#"
}